name: 'Upload Julia coveralls results'
description: 'Upload Julia test coverage results to codecov'
author: 'David Anthoff'

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:

branding:
  icon: 'upload'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - run: julia --color=yes -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
      shell: bash
